# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

workspace 'ios-sdk-examples'
project 'ios-sdk-examples-swift.xcodeproj'
project 'ios-sdk-examples-objc.xcodeproj'

def common_pods
  pod 'Map4dMap', '~> 2.4.0'
#  pod 'Map4dMap', :path => '~/work/map4d/mapes/platforms/ios/build/Release-universal-Prod/'
#  pod 'Map4dMapTest', :path => '~/work/map4d/mapes/platforms/ios/build/Map4dMapTest-2.4.0.b2/'
#  pod 'Map4dMapTest', :path => '/Users/huydc/Downloads/Map4dMapTest-2.4.0/'
end

target 'ios-sdk-examples-swift' do
  project 'ios-sdk-examples-swift.xcodeproj'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for ios-sdk-examples
  common_pods

end

target 'ios-sdk-examples-objc' do
  project 'ios-sdk-examples-objc.xcodeproj'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-sdk-examples-objc
  common_pods

end

